# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kiarash's Blog
email: kiarash.s@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stories from a developer
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://blog.kiarash.pro' # the base hostname & protocol for your site, e.g. http://example.com
cv_url: 'https://www.kiarash.pro'
author: 'Kiarash Soleimanzadeh'
twitter_username: KiarashSz
github_username: KiarashS
google_analytics: UA-49590121-6

# Build settings
#theme: minima
remote_theme: 'mmistakes/minimal-mistakes@4.19.1'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-include-cache
  - jekyll-gist
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# jekyll-archives:
#   enabled: 'all'
#   layouts:
#     year: year-archive
#     month: month-archive
#     day: day-archive
#     category: category-archive
#     tag: tag-archive

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

compress_html:
  clippings: all
  comments: ['<!-- ', ' -->']
  endings:
    [
      html,
      head,
      body,
      dt,
      dd,
      rt,
      rp,
      optgroup,
      option,
      colgroup,
      caption,
      thead,
      tbody,
      tfoot,
      tr,
      td,
      th,
    ]
  profile: false
  blanklines: false
  ignore:
    envs: []

defaults:
  # _posts
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts' # previously `post` in Jekyll 2.2.
    values:
      layout: single
      comments: true
      toc: false
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        overlay_image: https://raw.githubusercontent.com/KiarashS/BlogFiles/master/Statics/teaser.jpg
        overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  # _pages
  - scope:
      path: '_pages'
      type: 'pages'
    values:
      layout: single
      author_profile: true

paginate: 5
paginate_path: /page:num/

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: kiarash-soleimanzadeh-personal-blog

hyvor:
  website_id: 285

minimal_mistakes_skin: "contrast"
locale: "en"
title_separator: "|"
subtitle: "Stories from a developer"
name: "Kiarash Soleimanzadeh"
repository: "KiarashS/personal-blog"
# teaser: "https://raw.githubusercontent.com/KiarashS/BlogFiles/master/Statics/teaser2.jpg"
logo: "https://raw.githubusercontent.com/KiarashS/BlogFiles/master/Statics/ks2.png"
masthead_title: "Kiarash Soleimanzadeh"
search: true
comments:
  provider: "custom"

twitter:
  username: "KiarashSz"

google_site_verification: "dmDgFDL5MaTjdb7Zh-VIQuZuwRxVcTfp3cjYnmLmlug"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/KiarashSz"
    - "https://www.linkedin.com/in/kiarash-soleimanzadeh-4a767351"
    - "https://github.com/KiarashS"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-49590121-6"
    anonymize_ip: false # default

author:
  name     : "Kiarash's Blog"
  avatar   : "https://raw.githubusercontent.com/KiarashS/BlogFiles/master/Statics/me.jpg"
  bio      : "Researcher/Developer/CEO"
  location : "Iran"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-link"
      url: "https://www.kiarash.pro"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/KiarashSz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KiarashS"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kiarash-soleimanzadeh-4a767351"

footer:
  links:
    - label: "Kiarash Soleimanzadeh"
      icon: "fas fa-fw fa-link"
      url: "https://www.kiarash.pro"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/KiarashSz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KiarashS"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kiarash-soleimanzadeh-4a767351"

after_footer_scripts:
  - /assets/js/newwindowfix.js

breadcrumbs: false  # disabled by default
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

include:
  - _pages